[package]
name = "sfetch"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = { version = "2.1.0", default-features = false } # Minimal, no additional features
sysinfo = { version = "0.33.0", features = ["default"] } # Default system info features
